#ifndef __KEY1_H
#define __KEY1_H

#include "stm32f10x.h"

#define KEY1_EXIT_GPIO_CLK			 		RCC_APB2Periph_GPIOA
#define KEY1_EXIT_GPIO_PORT			 		GPIOA
#define KEY1_EXIT_GPIO_PIN			 		GPIO_Pin_0
#define KEY1_EXIT_GPIO_PORTSOURCE	  GPIO_PortSourceGPIOA
#define KEY1_EXIT_GPIO_PINSOURCE	  GPIO_PinSource0
#define KEY1_EXIT_LINE						  EXTI_Line0
#define KEY1_EXIT_IRQN							EXTI0_IRQn
#define KEY1_EXIT_IRQHANDLER				EXTI0_IRQHandler

#define KEY2_EXIT_GPIO_CLK			 		RCC_APB2Periph_GPIOC
#define KEY2_EXIT_GPIO_PORT			 		GPIOC
#define KEY2_EXIT_GPIO_PIN			 		GPIO_Pin_13
#define KEY2_EXIT_GPIO_PORTSOURCE	  GPIO_PortSourceGPIOC
#define KEY2_EXIT_GPIO_PINSOURCE	  GPIO_PinSource13
#define KEY2_EXIT_LINE						  EXTI_Line13
#define KEY2_EXIT_IRQN							EXTI15_10_IRQn
#define KEY2_EXIT_IRQHANDLER				EXTI15_10_IRQHandler


#define KEY1_STA GPIO_ReadInputDataBit(KEY1_EXIT_GPIO_PORT, KEY1_EXIT_GPIO_PIN)
#define KEY2_STA GPIO_ReadInputDataBit(KEY2_EXIT_GPIO_PORT, KEY2_EXIT_GPIO_PIN)


#define KEY_DN 1

void Key_Cfg(void);

#endif
